---
services:
  cffc-web:
    image: jsmit257/cffc-web:latest
    restart: always
    hostname: cffc-web
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8081:80
      - 8444:443
    volumes:
      - ./background/:/www/css/images/background/
      - ./album:/album
    environment:
      - CFFC_API_HOST
      - CFFC_API_PORT
      - AUTHN_HOST
      - AUTHN_PORT
      - SSL_HOST=localhost
      - SSL_PORT=8444
