#!/bin/sh

openssl req -x509 \
  -newkey rsa:4096 \
  -keyout key.pem \
  -out cert.pem \
  -sha256 \
  -days 3650 \
  -nodes \
  -subj "/C=US/ST=Colorado/L=Denver/O=huautla/OU=mycology/CN=cffc.io" \
  -addext "subjectAltName=DNS:cffc.io,IP:172.64.12.114,IP:10.0.0.4"
